export default {
    SEARCH_STARTED: 'SEARCH_STARTED',
    SEARCH_SUCCEEDED: 'SEARCH_SUCCEEDED',
    SEARCH_FAILED: 'SEARCH_FAILED',

    ELASTICSEARCH_STATUS_FETCHING: "ELASTICSEARCH_STATUS_FETCHING",
    ELASTICSEARCH_STATUS_DATA: "ELASTICSEARCH_STATUS_DATA",
    ELASTICSEARCH_STATUS_ERROR: "ELASTICSEARCH_STATUS_ERROR",

    ELASTICSEARCH_SAMPLE_RESET_POSTING: "ELASTICSEARCH_SAMPLE_RESET_POSTING",
    ELASTICSEARCH_SAMPLE_RESET_OK: "ELASTICSEARCH_SAMPLE_RESET_OK",
    ELASTICSEARCH_SAMPLE_RESET_ERROR: "ELASTICSEARCH_SAMPLE_RESET_ERROR",
}